### ISSUE TITLE
Can't unbox a date or a date-time

### ISSUE THREAD

**Issue by hmalmedal** [jeroenooms/jsonlite#100]
When I try to unbox a date or a date-time I get an error.

``` r
jsonlite::unbox(as.Date("2001-01-01"))
```

    ## Error: Only atomic vectors of length 1 or data frames with 1 row can be unboxed.

``` r
jsonlite::unbox(as.POSIXct("2001-01-01"))
```

    ## Error: Only atomic vectors of length 1 or data frames with 1 row can be unboxed.

**Comment by jeroenooms** [comment]
Mmm good catch. I pushed a fix: https://github.com/jeroenooms/jsonlite/commit/21dc47bcc5d11bd3c53850fe8e707e40dbfc4afa

**Comment by jeroenooms** [comment]
Fix is on cran now.
