### ISSUE TITLE
error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by sergeetiparent** [jeroenooms/jsonlite#101]
On install, with R 3.2.1, x86_64-suse-linux-gnu (64-bit).

    collapse_array.c: In function ‘C_collapse_array’:
    collapse_array.c:12:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int i=0; i<len; i++) {
       ^

**Comment by jeroenooms** [comment]
Why is your compiler not using `-std=gnu99` ?
