### ISSUE TITLE
Can't handle a newline character at the beginning of a text field

### ISSUE THREAD

**Issue by retrography** [jeroenooms/jsonlite#103]
The following valid JSON code can not be parsed and produces an invalid character error:

```json
{"description":"\u000a    \u00e8\u00a7\u00a324\u00e7\u0082\u00b9\u00e3\u0080\u0082computes an expression to solve the 24 game if possible.\u000a  "}
```

It is the first newline character that generates the error.

**Comment by jeroenooms** [comment]
I think the newline character must be escaped with `\n` instead of `\u000a`. The [rfc4627](http://ietf.org/rfc/rfc4627.txt) spec says:

> All Unicode characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

**Comment by retrography** [comment]
The code is coming directly from a database server that generates valid json (orientdb). It has supposedly been escaped correctly (fetched using RCurl). That is how I see it in the web browser but then if I replace all "\n"s with spaces, the parser works. The same json passes correctly through a ruby validator. Is there any way I can check this and report back? I can probably save the http response directly to a file...

**Comment by jeroenooms** [comment]
The json is fine, I think the problem appears why you try to enter it in the R terminal. This works:

```r
jsonlite::fromJSON("http://pastebin.com/raw.php?i=2xXRQuPK")
```

And so does this:

```r
tmp <- tempfile()
download.file("http://pastebin.com/raw.php?i=2xXRQuPK", tmp)
x <- readLines(tmp, warn = FALSE)
jsonlite::fromJSON(x)
```

**Comment by retrography** [comment]
I tried once again, and the same happens. So I post the `dput` of my actual JSON here for you to test:

```json
"{\"result\":[{\"@type\":\"d\",\"@rid\":\"#12:16\",\"@version\":62,\"@class\":\"Package\",\"title\":\"24games-0.2.1\",\"gem\":\"24games\",\"update\":\"2011-01-17\",\"date\":\"2011-01-16\",\"yanked\":false,\"atom_up\":\"2011-01-17\",\"downloads\":7970,\"ruby_version\":\">= 0\",\"version\":\"0.2.1\",\"platform\":\"ruby\",\"file_size\":7168,\"lib_count\":4,\"out_IS_VERSION_OF\":[\"#24:16\"],\"in_AUTHORED\":[\"#35:999805\"],\"in_COVERS\":[\"#38:155856\"],\"authors\":[\"takafan\"],\"dependencies\":{\"development\":[],\"runtime\":[]},\"description\":\"\n    è§£24ç\u0082¹ã\u0080\u0082computes an expression to solve the 24 game if possible.\n  \",\"email\":\"takafan@hululuu.com\",\"executables\":[\"24games\"],\"has_rdoc\":true,\"homepage\":\"http://github.com/takafan/24games\\\"\",\"licenses\":[],\"require_paths\":[\"lib\"],\"rubyforge_project\":\"24games\",\"rubygems_version\":\"1.3.7\",\"specification_version\":3,\"summary\":\"24 game/Solve\",\"file_count\":11,\"out_Includes\":[\"#57:4619624\",\"#57:4619625\",\"#57:4619626\",\"#57:4619627\"],\"doc_count\":0,\"test_count\":0,\"datediff\":1,\"@fieldTypes\":\"update=t,date=t,atom_up=t,out_IS_VERSION_OF=g,in_AUTHORED=g,in_COVERS=g,out_Includes=g\"}]}"
```

Please note that the exact same string parses correctly on `RJSONIO`, so there must be an issue somewhere...

**Comment by jeroenooms** [comment]
RJSONIO has a graceful parser which tries to parse JSON, even when invalid, which sometimes leads to unexpected output. Because jsonlite uses yajl it is more strict on the json, hence you get an error when it is invalid json.

But both `jsonlite::validate` as well as `RJSONIO::isValidJSON` will tell you this json is invalid because it contains strings with unescaped linebreaks.

**Comment by retrography** [comment]
I actually tested this now, and `RJSONIO::isValidJSON` returns true, while `jsonlite::validate` returns false. Do you think I have to file a bug for `RJSONIO` then?
