### ISSUE TITLE
Specification of significant digits

### ISSUE THREAD

**Issue by Planeshifter** [jeroenooms/jsonlite#104]
I ran into an issue with the output of the `toJSON` function when specifying a large number of significant digits. Take a look at the following example:

```R
library(jsonlite)
options(digits=22)

qcauchy( 0.1 ) 
# returns -3.077683537175254002705

toJSON( qcauhy( 0.1 ), digits = 22 )
# -3.07768353717525
```
It seems as if the maximum number of significant digits after the period that one can specify is `14`. The `toJSON` function of the `RJSONIO` package does not have this problem, yet I prefer the API of `jsonlite`. Any ideas how to fix this?

**Comment by jeroenooms** [comment]
A double doesn't have that much precision. I suspect that whatever gets printed after the 15th or so digit is noise. Try in R:

```r
options(digits=22)
print(pi)
```

And compare that to the real value of π from wikipedia.

**Comment by Planeshifter** [comment]
Thanks for the quick reply! Since this is intended behaviour of the `toJSON` function then, I will close this issue.
