### ISSUE TITLE
Error: invalid char in json text

### ISSUE THREAD

**Issue by briatte** [jeroenooms/jsonlite#106]
Hi,

This is probably a newbie question.

I'm re-running some code that used to work fine about six months ago. I'm using `jsonlite::fromJSON(flatten = TRUE)` and getting the following error:

```
Error in feed_push_parser(buf) : 
  lexical error: invalid char in json text.
                                       ﻿{"dokumentstatus":{"dokument
                     (right here) ------^
```

[Here's the data file.](https://gist.github.com/briatte/c5a72004359659a287b9)

Am I doing something wrong?

**Comment by jeroenooms** [comment]
Are you running the latest version? It works fine here:

```r
mydata <- fromJSON("https://gist.githubusercontent.com/briatte/c5a72004359659a287b9/raw/222c77f538cd3a7168423d2830e49bb091c8a29d/gc02a1.json")
```

Try upgrading: `install.packages("jsonite")`

**Comment by briatte** [comment]
You're right, this also works at home… Something is super-weird here.

The file comes from a ZIP that I'm locally unzipping before parsing the contents (could not find a way to use `fromJSON` on a connection created by `unz`). Here's a reproducible example that fails to work:

```r
library(jsonlite)
dir.create("exampledata")

download.file("http://data.riksdagen.se/dataset/dokument/mot-2014-2017.json.zip",
              "mot-2014-2017.json.zip", mode = "wb")

unzip("mot-2014-2017.json.zip", exdir = "exampledata")
f = list.files("exampledata", pattern = "json$", full.names = TRUE)

for(j in f) {
  
  d = fromJSON(j, flatten = TRUE)$dokumentstatus
  
  cat("hangar_id:", d$dokument$hangar_id, "doc:", d$dokument$dok_id, "\n")

}
```

Using `jsonlite` 0.9.16.

**Comment by jeroenooms** [comment]
I think I know the problem. Your json files are prefixed with a byte order mark (BOM) which is now allowed according to the spec. The regular parser however is more graceful than the stream parser (which is used to stream from disk). 

You can easily avoid the problem by reading the file into memory and then parse it:

```r
d = fromJSON(readLines(j), flatten = TRUE)$dokumentstatus
``` 

I'll see if I can make the stream parser behave the same as the string parser.

**Comment by briatte** [comment]
Yep, that's what I've ended up doing.

Bonus question–is there any way to make this example work without unzipping the files to disk? I'd love to go with `unz` but must confess that I'm useless with file connections (and ended up creating a huge memory leak last time I tried).

**Comment by jeroenooms** [comment]
I have pushed a fix so now the code above should parse JSON and give you a warning about the illegal byte order mark.

**Comment by jeroenooms** [comment]
It should be possible to stream data from the zip, but it looks like you need to know the name of the file within the zip in advance. But something like this should work (with the fixed version):

```r
con <- unz("mot-2014-2017.json.zip", "h2021.json")
h2021 <- fromJSON(con)
```

**Comment by briatte** [comment]
Thank you very much for the fix, the new version does exactly what I need.

**Comment by FahmiRR** [comment]
Hi, I also encounter this issue when doing this code:

`for (n in listsample){
  namajson <- glue("{n}.json")
  bukajson <- fromJSON(namajson)
  print(jsonfile)
}`

Following error happen
`Error: lexical error: invalid char in json text.
                                        xxxxxxxx.json xxx.j
                 (right here) ------^`

Meanwhile when I entering manually
`bukajson <- fromJSON("xxx.json")`

It works normally

the list sample file is 
`'data.frame':	66 obs. of  1 variable:
 $ username: chr  "xxx" "xxx" "xxx" "xxx" ...`

Anyhelp?

**Comment by jeroen** [comment]
Try `print(namajson)` to see the file you are trying to read because apparently it does not exists.

**Comment by FahmiRR** [comment]
Whoops, sorry it was assigned in different file, 

Here we go

```
print(namajson)
xxx.json
yyyy.json
```

I also tried to put double quotes

```
for (n in listsample){
  namajson <- glue('\"{n}.json\"')
  bukajson <- fromJSON(namajson)
  print(namajson)
}
```

and for namajson it print

```
print(namajson)
"xxxx.json"
"yyyy.json"
```

but now It produce different error

```
Error: parse error: trailing garbage
          aidir_ezz.json" "loryngg.json" "ajaiskskdkkd.json" "desi_pur
                     (right here) ------^
```
