### ISSUE TITLE
NA's not always encoded as null by toJSON

### ISSUE THREAD

**Issue by hampei** [jeroenooms/jsonlite#109]
```
> jsonlite::toJSON(NA)
[null]
> jsonlite::toJSON(as.numeric(NA))
["NA"]
```

So when NA/3 will suddenly return "NA". 

Running jsonlite_0.9.16

**Comment by jeroenooms** [comment]
This is expected, see section 2.1.1 of the [jsonlite paper](http://arxiv.org/pdf/1403.2805v1.pdf). You can control this with the `na` parameter:

```r
x <- list(foo = c(T, F, NA), bar = (1, pi, NA))
jsonlite::toJSON(x)
jsonlite::toJSON(x, na = "string")
jsonlite::toJSON(x, na = "null")
```

**Comment by hampei** [comment]
Ok, wrong repo, but is there a way to have opencpu use the na="null" version everywhere? Since now I have this ugly line in way too many places to change NA's to logical NA's. 
I can't imagine anyone ever wanting a string "NA" in the results, were they are expecting a numeral.

**Comment by jeroenooms** [comment]
You can use `/json?na=null` for example:

```
https://public.opencpu.org/ocpu/tmp/x009b322c58/R/.val/json
https://public.opencpu.org/ocpu/tmp/x009b322c58/R/.val/json?na=string
https://public.opencpu.org/ocpu/tmp/x009b322c58/R/.val/json?na=null
```

**Comment by hampei** [comment]
Ah, dank.
