### ISSUE TITLE
fromJSON supports for big integer

### ISSUE THREAD

**Issue by jangorecki** [jeroenooms/jsonlite#111]
```r
suppressPackageStartupMessages({
    library(jsonlite)
    library(bit64)
})
x = as.integer64(2)^60 + 1:3
bigintjson = toJSON(x)
i = fromJSON(bigintjson)
class(x)
# [1] "integer64"
class(i)
# [1] "numeric"
format(x, scientific=FALSE)
# [1] "1152921504606846977" "1152921504606846978" "1152921504606846979"
format(i, scientific=FALSE)
# [1] "1152921504606846976" "1152921504606846976" "1152921504606846976"
packageVersion("jsonlite")
# [1] ‘0.9.16’
```
Any code which relies on big int (or may rely on big int in future) cannot be used with jsonlite due to integer rounding to numeric. I would like to see such option, so filling this FR.
It can be hard to distinct int from big int while processing so the easiest would be just to give option to process any integer fields as big integers.
If this feature is not on the roadmap for any time soon maybe we could have a workaround and parse integers as character so user can convert them manually later without losing precision.

**Comment by jeroenooms** [comment]
There is an option `bigint_as_char`:

```r
library(jsonlite)
library(bit64)
x = as.integer64(2)^60 + 1:3
bigintjson = toJSON(x)
out = fromJSON(bigintjson, bigint_as_char = TRUE)
as.integer64(out)
```

However I strongly recommend against using big integers with JSON because they are not interoperable. The JavaScript JSON parser e.g. will turn them into doubles. Try pasting your json with big integers into [jsonlint](http://jsonlint.org/) for example.

**Comment by sergiospagnuolo** [comment]
> There is an option `bigint_as_char`:
> 
> ```r
> library(jsonlite)
> library(bit64)
> x = as.integer64(2)^60 + 1:3
> bigintjson = toJSON(x)
> out = fromJSON(bigintjson, bigint_as_char = TRUE)
> as.integer64(out)
> ```
> 
> However I strongly recommend against using big integers with JSON because they are not interoperable. The JavaScript JSON parser e.g. will turn them into doubles. Try pasting your json with big integers into [jsonlint](http://jsonlint.org/) for example.
> 
> Hence encoding big integers in JSON is very risky. You are better of storing them as strings.

This is a very good solution almost a decade later
