### ISSUE TITLE
Any idea on supporting JsonPath?

### ISSUE THREAD

**Issue by renkun-ken** [jeroenooms/jsonlite#112]
Sometimes it is super convenient to use XPath-like query to query data in a json, like what [JsonPath](https://github.com/jayway/JsonPath) does. Any idea on supporting this?

**Comment by jeroenooms** [comment]
Unless there is a simple C implementation available, I think it would be easier to do this in a separate package.

**Comment by renkun-ken** [comment]
Sadly it seems no C-implementation of JPath is available at the moment.

**Comment by jeroenooms** [comment]
Are you aware of [jq](https://stedolan.github.io/jq/) and [jqr](https://github.com/ropensci/jqr) ?

**Comment by renkun-ken** [comment]
Thanks for your links! I'll take a look at it :)

**Comment by timelyportfolio** [comment]
There's always `V8` for the various JavaScript libraries.  I have a list somewhere of JavaScript Xpath-like libraries that I put together at some point.  @renkun-ken, would that be helpful?

**Comment by renkun-ken** [comment]
Thanks @timelyportfolio! Would you like to provide some example?

**Comment by timelyportfolio** [comment]
Have not found my list yet, but I remember this one https://github.com/s3u/JSONPath and this StackOverflow [post](http://stackoverflow.com/questions/8481380/is-there-a-json-equivalent-of-xquery-xpath) (**out of date**)..  I'll try to work up an example in `R`/`V8`.

**Comment by timelyportfolio** [comment]
An example in `R`:

```
library(V8)

ctx <- new_context(global = "window")
ctx$source(
  "https://rawgit.com/s3u/JSONPath/master/lib/jsonpath.js"
)
ctx$eval(
'
var books = {
"store": {
"book": [
{
  "category": "reference",
  "author": "Nigel Rees",
  "title": "Sayings of the Century",
  "price": 8.95
},
  {
  "category": "fiction",
  "author": "Evelyn Waugh",
  "title": "Sword of Honour",
  "price": 12.99
  },
  {
  "category": "fiction",
  "author": "Herman Melville",
  "title": "Moby Dick",
  "isbn": "0-553-21311-3",
  "price": 8.99
  },
  {
  "category": "fiction",
  "author": "J. R. R. Tolkien",
  "title": "The Lord of the Rings",
  "isbn": "0-395-19395-8",
  "price": 22.99
  }
  ],
  "bicycle": {
  "color": "red",
  "price": 19.95
  }
}
}
'
)

ctx$get('JSONPath({json:books,path:	"$..book[?(@.price<10)]"})')

```
