### ISSUE TITLE
fromJson can not handle \r\n

### ISSUE THREAD

**Issue by gaizoule** [jeroenooms/jsonlite#115]
jsonlite::fromJson cannot handle string including \r\n

jsonlite::fromJSON('["\\u5bff\u53f8\r\n","Z\\u00fcrich"]')
Error in parse_string(txt, bigint_as_char) : 
  lexical error: invalid character inside string.
                             ["\u5bff司  ","Z\u00fcrich"]
                     (right here) ------^

while rjson can handle

 rjson::fromJSON('["\\u5bff\u53f8\r\n","Z\\u00fcrich"]')
[1] "寿司\r\n" "Zürich"

**Comment by jeroenooms** [comment]
This is invalid JSON. Dupe @ https://github.com/jeroenooms/jsonlite/issues/47
