### ISSUE TITLE
Feature request: set accept header in fromJSON()

### ISSUE THREAD

**Issue by maarten-vermeyen** [jeroenooms/jsonlite#117]
Some REST API's support multiple representations of a resource on the same url (eg.: HTML, JSON and XML). In this case the client needs to specify an accept header in order to tell the server which representation of the resource to send back.

I think it would be nice to set an `accept: application/json` header by default and making this overwritable with a parameter to the fromJSON() function. If NULL is passed, no header should be included in the request. The parameter should be ignored if txt is not a http(s) url.

I've taken a first look at the code. It seems to me that all that would be required is defining a handler for the curl() call in fromJSON.R. (I haven't actually ran this code).

``` R
fromJSON <- function(txt, simplifyVector = TRUE, simplifyDataFrame = simplifyVector,
  simplifyMatrix = simplifyVector, flatten = FALSE, acceptHeader='application/json', ...) {

  # check type
  if (!is.character(txt) && !is(txt, "connection")) {
    stop("Argument 'txt' must be a JSON string, URL or file.")
  }

  # overload for URL or path
  if (is.character(txt) && length(txt) == 1 && nchar(txt, type="bytes") < 10000) {
    if (grepl("^https?://", txt, useBytes=TRUE)) {
      loadpkg("curl")
      h <- curl::new_handle()
      if (!is.null(acceptHeader)) {
          curl::handle_setheaders(h, "Accept" = acceptHeader)
      }
      txt <- curl::curl(txt, h)
    } else if (file.exists(txt)) {
      # With files we can never know for sure the encoding. Lets try UTF8 first.
      # txt <- raw_to_json(readBin(txt, raw(), file.info(txt)$size));
      txt <- file(txt)
    }
  }
```
If you agree with this approach, I would be happy to prepare a pull request for comments and validation.

**Comment by maarten-vermeyen** [comment]
Although I feel a function called fromJSON should set the header, we could also set the acceptHeader to `NULL` by default. This would pretty much guarantee backwards compatibility.

**Comment by jeroenooms** [comment]
Thanks. Actually we [used to have this](https://github.com/jeroenooms/jsonlite/blob/v0.9.12/R/download.R#L17-L20) but it got lost when we switched to `curl`. I'll put it back.

I don't think this has to be optional, jsonlite only understands json content so it seems like a reasonable default. We'll try it and see if something breaks :-)

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/jsonlite/commit/441e3e79005fcc8693b38713766d23532b254e4d

**Comment by jeroenooms** [comment]
Thanks!
