### ISSUE TITLE
exical error: invalid char in json text

### ISSUE THREAD

**Issue by hexindent** [jeroenooms/jsonlite#119]
I'm using `fromJSON` to import data and it can't even parse the first line:

    > meta_cellphones <- fromJSON('meta_cellphones.json')
    Error: lexical error: invalid char in json text.
                                          {'asin': '0110400555', 'related'
                         (right here) ------^

Is 'a' not a valid char here? The JSON file starts like this:

    {'asin': '0110400555', 'related': {'also_bought': ['B00C56IXUG', 'B008ZFQWOK'], 'also_viewed': ['B008N7OOLS', 'B00C56ICFG']}, 'brand': '', 'categories': [['Cell Phones', 'Cases']], 'description': 'Compatible with Apple iPhone 4 4G 4S 16/32/64 GB\\nColor: Pink & White'}

Thanks for any suggestion!

**Comment by jeroenooms** [comment]
JSON requires double quotes for all strings

**Comment by hexindent** [comment]
Thanks! I just checked with the guy who gave me the data. He uses Python `eval` and he's not tight on strict JSON. Seems like R doesn't support this and some extra work is needed.

**Comment by jeroenooms** [comment]
There is no such thing as strict json. Your json is simply invalid. You can validate it on a website like http://jsonlint.com/ or using the `validate()` function in jsonlite.

**Comment by bcaessens** [comment]
Hi all,
I have a similar issue (I think). I wrote json strings to a database (postgresql). However, when I read them back in R using jsonlite, the validate function gives me an invalid response. But, jsonlint says the json string is valid. In addition, validate errors on the \n character, but fromJSON errors on the opening quote. 

Here is the beginning of jsonstring:

`"[{'view_history': '[{\"page_index\":0,\"viewing_time\":14247},{\"page_index\":1,\"viewing_time\":3104},{\"page_index\":2,\"viewing_time\":3075}]'`

here is the output of 
```
cat(jsonstring)
[{'view_history': '[{"page_index":0,"viewing_time":14247},{"page_index":1,"viewing_time":3104},{"page_index":2,"viewing_time":3075}]'

```
Here is the response using fromJSON(jsonstring):
```
> fromJSON(x)
Error: lexical error: invalid char in json text.
                                     [{'view_history': '[{"page_index"
                     (right here) ------^
```
and validate(jsonstring):
```
> validate(x)
[1] FALSE
attr(,"offset")
[1] 3
attr(,"err")
[1] "lexical error: invalid char in json text.\n                                     [{'view_history': '[{\"page_index\"\n                     (right here) ------^\n"
```

However, pasting the jsonstring in jsonlint.com and validating says VALID JSON. 

Any thoughts on what's going on?

kind regards,
Bernie.

**Comment by jeroen** [comment]
JSON strings and keys **must** use double quotes. Your string above has single quotes.

**Comment by bcaessens** [comment]
Hi Jeroen,

Thanks for your fast response. I have read about the single versus double quotes a lot. But I am still kind of lost here (and I guess I am not alone :-). Just to make sure and resolve this issue:

'view_history' should be "view_history" (and so on)? 

I begin to understand that python's json.dump() does not dump a json string!! Let's see if we can fix this easily. Thanks again. 
bernie

**Comment by jeroen** [comment]
Yes all strings in json must be double quoted. I can't imagine your string passes at https://jsonlint.com/ because it will also require double quotes.

**Comment by bcaessens** [comment]
My mistake Jeroen. Sorry 'bout that. I copy-paste the R output of my variable in jsonlint. I didn't think the whole string is double-quoted "[{ 'view_history' ...]}". So, this passes. Removing the quotes clearly gives me the invalid string, just like jsonlite does. 

Sorry for the confusion. 
Bernie.

**Comment by isomorphisms** [comment]
I still get this error from `httr`, which I assume must use your library: `httr::POST("https://www.tumblr.com/oauth/request_token") %>% content`


[Error: lexical error: invalid char in json text.
                                       oauth_consumer_key required
                     (right here) ------^](url)

**Comment by Singht9** [comment]
> There is no such thing as strict json. Your json is simply invalid. You can validate it on a website like http://jsonlint.com/ or using the `validate()` function in jsonlite.



> I'm using `fromJSON` to import data and it can't even parse the first line:
> 
> ```
> > meta_cellphones <- fromJSON('meta_cellphones.json')
> Error: lexical error: invalid char in json text.
>                                       {'asin': '0110400555', 'related'
>                      (right here) ------^
> ```
> Is 'a' not a valid char here? The JSON file starts like this:
> 
> ```
> {'asin': '0110400555', 'related': {'also_bought': ['B00C56IXUG', 'B008ZFQWOK'], 'also_viewed': ['B008N7OOLS', 'B00C56ICFG']}, 'brand': '', 'categories': [['Cell Phones', 'Cases']], 'description': 'Compatible with Apple iPhone 4 4G 4S 16/32/64 GB\\nColor: Pink & White'}
> ```
> Thanks for any suggestion!

Hi, were you able to read this data in R or using Python ? am also trying to work on this data, if can read it !! Thanks much :)

**Comment by mpr1255** [comment]
FYI also having an issue with `validate()`. I have 'valid' files (i.e. I can read them in with jsonlite and Node and whatever), but `validate()` returns `FALSE`. My files also have double quotes. Here's an example: 

`{"bang":1,"magicwish":"n","blah":"al;kjklajlasosa88900","failed":none}`
(changed values obviously)

**Comment by jeroen** [comment]
Your json is invalid, you need to put quotes around `none`

**Comment by mpr1255** [comment]
Honestly -- the response I am getting from the server is in this form. First item has no quotes, second doesn't, third does, fourth does, fifth doesn't. (I altered it above). Anyway, I used `jsonvalidate` to make a schema based on this idiosyncratic format and solved my problem that way.
