### ISSUE TITLE
Return NA values for list columns with missing values

### ISSUE THREAD

**Issue by momeara** [jeroenooms/jsonlite#120]
I am trying to read JSON data into R that is an array of rows having a list column that has missing values.<sup>1</sup> For example,

```
{
    "table1" : [{
        "col1" : "val1a"

    }, {
        "col1" : "val1b",
        "col2" : ["val2b", "val2bb"]
    }]
}

```

I can use the `jsonlite` to parse the data,

```
library(jsonlite)
library(dplyr)
library(tidyr)

raw_json_data <- "{\"table1\":[{\"col1\" : \"val1a\"},{\"col1\":\"val1b\",\"col2\":[\"val2b\", \"val2bb\"]}]}" 
fromJSON()
data <- fromJSON(raw_json_data)
```

However, `col2` has a `NULL` value in it rather than a `NA` as I would have expected.
```
> data$table1
    col1          col2
 1 val1a          NULL
 2 val1b val2b, val2bb
```

The `NULL` value is a problem, because when trying to unpack `col2` using `tidyr` 

```
data %>% unnest(col2)
```

it results in a segmentation fault.  I don't think `tidyr` should seg-fault when presented with `NULL`s. None-the-less I think `fromJSON` should have an `NA` value rather than `NULL` value here, because then it's possible to use element-wise functions on the columns.

I've cross-posted this bug to `tidyr`, hadley/tidyr#141.
<hr>
<sup>1</sup>E.g. the uniprot_ids column from genenames.org has missing values for some genes.

**Comment by jeroenooms** [comment]
jsonlite is doing the right thing here: https://github.com/hadley/tidyr/issues/141
