### ISSUE TITLE
Incomplete parsing

### ISSUE THREAD

**Issue by mathiasimmer** [jeroenooms/jsonlite#121]
I'm not entirely sure what happens but I'm pretty sure that I have encountered a bug.
I tried to parse https://www.reddit.com/r/CFB/comments/3ucmh0/honouring_tradition_huskies_will_wear_practice/.json?sort=new
using
`result<-fromJSON(txt = "https://www.reddit.com/r/CFB/comments/3ucmh0/honouring_tradition_huskies_will_wear_practice/.json?sort=new")`

however the result seems kinda odd: 
![image](https://cloud.githubusercontent.com/assets/8802601/11427077/96620c56-9460-11e5-86f0-9439bb8efa03.png)

EDIT: The JSON as time of writing this post: http://pastebin.com/2dkLqAdF
I am using jsonlite version 0.9.18

**Comment by jeroenooms** [comment]
The json is being parsed correctly but it is nested. Therefore the rstudio viewer cannot easily display it in a table.

**Comment by mathiasimmer** [comment]
But how come the "modhash" is empty? It should contain some simple strings but even if I run in command-line, I get an empty result?
![image](https://cloud.githubusercontent.com/assets/8802601/11427658/04a220c6-9465-11e5-862a-41b2e7a55783.png)

**Comment by jeroenooms** [comment]
Works for me:

```r
> result <- fromJSON("http://pastebin.com/raw.php?i=2dkLqAdF")
> result$data$modhash
[1] "td7rosbec293bb417c988422af833889dd720b14aa28a0cbe0" "td7rosbec293bb417c988422af833889dd720b14aa28a0cbe0"
```

**Comment by mathiasimmer** [comment]
Wow this is weird. There seems to be a difference between the copy/paste in Pastebin and when using directly from reddit. The value should never be empty. If I load from Pastebin it works fine, but not if directly from Reddit.
