### ISSUE TITLE
stream_in - defining a custom handler for preprocessing

### ISSUE THREAD

**Issue by duf59** [jeroenooms/jsonlite#124]
I would like to read relatively large json file in R using jsonlite and them select only a few variables.
I have tried with the following code (selecting only 2 fields from the flattened dataframe):

``` {r}
stream_in(bzfile(file), pagesize = 1000) %>%
    flatten(recursive = TRUE) %>%
    select(timestamp   = `_source.@timestamp`, id       = `_source.@fields.id`)
```

With the above code, the whole file needs to fit in memory since filtering occurs after streaming in.
I was wondering if there is anyway to use the handler argument to perform this filtering step on each page while streaming in?

I did came across the following example:

``` {r}
stream_in(con_in, handler = function(df){
df <- dplyr::filter(df, distance > 1000)
df <- dplyr::mutate(df, delta = dep_delay - arr_delay)
stream_out(df, con_out, pagesize = 1000)
}, pagesize = 5000)
```

But it requires writing and then re-reading the files, which would add some overhead in my case.
Being able to do some processing while reading would be very convenient.
I'm not quite sure how to implement that nor if it does require changing the source code ([this bit](https://github.com/jeroenooms/jsonlite/blob/master/R/stream.R#L127)).

Any input would be greatly appreciated!
thanks!

**Comment by jeroenooms** [comment]
Does this example help? https://gist.github.com/jeroenooms/5f10d2e19c4ac785edad

**Comment by duf59** [comment]
Yes , exactly what I was looking for thanks!!

**Comment by niklasvm** [comment]
I am looking for assistance with defining a custom handler. The link above no longer works.
