### ISSUE TITLE
handling attributed vector

### ISSUE THREAD

**Issue by randy3k** [jeroenooms/jsonlite#13]
First of all, thanks very much for the package, i like it more than RJSONIO, etc..

Current implementation of jsonlite ignores the name attributes of a vector, to see this, consider

```
> cat(jsonlite::toJSON(c(a=1,b=2)))
[ 1, 2 ]
```

The resulting json is an array.
Comparing to `RJSONIO`, which keep the attributes and change the output to a dictionary.

```
> cat(RJSONIO::toJSON(c(a=1,b=2)))
{
 "a":      1,
"b":      2 
}
```

It may be useful to add an option `use.name`. 
If `use.name` is off, output `[ 1, 2 ]`, otherwise output `{ "a": 1, "b": 2}`. `RJSONIO` actually has a similar option `.withNames`.

**Comment by petrelharp** [comment]
As someone who uses named vectors all the time (great for error checking), I'm putting in my vote for this being a useful thing to figure out.  Here's a naive suggestion: why not add attributes in a list, for instance, turning
```
  c(a=1,b=2,c=3)
```
into
```
  { [1,2,3], .attributes={ names : ["a","b","c"] } }
```

This would be a bit uglier in the output, but this could be an optional switch, and would be easy to recognize in the inverse transform.
