### ISSUE TITLE
Use stri_escape_unicode to escape Unicode characters

### ISSUE THREAD

**Issue by asieira** [jeroenooms/jsonlite#131]
Add a new option to `toJSON` that makes non-ASCII characters to be escaped using `\u<unicode>`, perhaps using stri_escape_unicode.

This would be similar to the `ensure_ascii` option that exists in the Python json module:
```
>>> json.dumps('áéíóú', ensure_ascii = True)
'"\\u00e1\\u00e9\\u00ed\\u00f3\\u00fa"'
```

**Comment by jeroenooms** [comment]
The latest spec states that json is always utf8, so there is really no reason for escaping it anymore. I don't plan to add a heavy dependency as stringi to `jsonlite`.

**Comment by asieira** [comment]
If jsonlite converts whatever encodes it gets as input to UTF-8 and this is fully documented, I agree this is much simpler.
