### ISSUE TITLE
Need to export numeric (double) value with digits to distinguish from integer

### ISSUE THREAD

**Issue by renkun-ken** [jeroenooms/jsonlite#132]
I'm using `toJSON` to produce a JSON representation of a nested list so that I can import it to a mongodb. Later I'll use c++ to access the mongodb which is strict on the data types of fields I query.

Suppose  

```
list(a = 1, b = 2L)
```

How can I produce a JSON string like 

```
{
  "a": 1.0,
  "b": 2
}
```

in which `1.0` is necessary to ensure the imported field is double rather than integer.

**Comment by jeroenooms** [comment]
Currently there is no such option. We could add an option like that, but the tricky thing is how this will generalize to really large numbers, e.g. `1e20`. See also discussion here: https://jira.mongodb.org/browse/CDRIVER-652

**Comment by jeroenooms** [comment]
Experimental support for a `force_decimals` parameter in `toJSON`: https://github.com/jeroenooms/jsonlite/commit/ce34567e56678553ddc1417b90817372ebd671dc. Needs more testing.

```r
> x <- 10^c(-10:20)
> prettify(toJSON(x, force_decimal = TRUE))
[
    1e-10,
    1e-09,
    1e-08,
    1e-07,
    1e-06,
    1e-05,
    0.0001,
    0.001,
    0.01,
    0.1,
    1.0,
    10.0,
    100.0,
    1000.0,
    10000.0,
    100000.0,
    1000000.0,
    10000000.0,
    100000000.0,
    1000000000.0,
    10000000000.0,
    100000000000.0,
    1000000000000.0,
    10000000000000.0,
    100000000000000.0,
    1e+15,
    1e+16,
    1e+17,
    1e+18,
    1e+19,
    1e+20
]
```

**Comment by jeroenooms** [comment]
This now works in the dev version of mongolite:


```r
library(mongolite)
x <- -10:10
df <- data.frame(x = x, y = as.numeric(x))
m <- mongo("testnum")
m$insert(df)
df2 <- m$find()
identical(df, df2)
```

**Comment by renkun-ken** [comment]
Looks nice! Thanks!

**Comment by jeroenooms** [comment]
Does this solve your problem? Are you using mongolite or some other way to import into mongo?

**Comment by renkun-ken** [comment]
I'm using mongolite to import json files. This does solve my problem, thanks!

**Comment by renkun-ken** [comment]
Same issue as requested in https://github.com/jeroenooms/mongolite/issues/38.

**Comment by jeroen** [comment]
Yes it's stable, you can use it.

**Comment by omgmvi** [comment]
> Yes it's stable, you can use it.

Hi!, please add it to the documentation! (I was luky to find this thread to solve my problem). Thanks for the package anyway!
