### ISSUE TITLE
Need more accurate control of rendering scalar or array

### ISSUE THREAD

**Issue by renkun-ken** [jeroenooms/jsonlite#133]
Suppose the following json:

```json
{
  "x": 1,
  "y": [1, 2, 3],
  "z": [ { "a": 1, "b": 2}, { "a": 2, "b": 3} ],
  "w": {
    "p": [ 1 ],
    "q": {
      "m1": [1, 2, 3],
      "m2": "hello"
    }
  }
}
```

If a json is only used within R, whether `w.p` is a vector or a scalar does not matter. But if this produced json is to be read from C++ or other strong type languages, it does matter to distinguish a vector from a scalar.

Currently, `toJSON(..., auto_unbox = TRUE)` produces scalar representation from one-element vector. But in many cases, we need more accurate control. For example, we may need `x` to be scalar, but `w.p` to be vector no matter whether it is supplied one or more elements.

It would be nice to have a function to hint the json generator like

```r
toJSON(list(
  x = scalar(1),
  y = c(1, 2, 3),
  z = list(list(a = scalar(1), b = scalar(2)), list(a = scalar(2), b = scalar(2))),
  w = list(p = 1, q = list(m1 = c(1, 2, 3), m2 = scalar("hello")))
))
```

where `scalar()` hints that the value must be rendered as scalar value, everything else produces vector;

or 

```r
toJSON(list(
  x = 1,
  y = c(1, 2, 3),
  z = list(list(a = 1), b = 2), list(a = 2, b = 2)),
  w = list(p = json_array(1), q = list(m1 = c(1, 2, 3), m2 = "hello"))
))
```

where `json_array()` hints that the value must produce an array representation, otherwise, one-element value should produce a scalar, and zero-element and multi-element vector should produce array.

I'm not sure if it is a good design, but if it supports more accurate control over whether to produce a scalar or an array on a field basis, it would certainly make the produced json much more predictable and more easily for other strong-typed languages to work with.

**Comment by jeroenooms** [comment]
I think we have this. With the default `toJSON` settings you use `unbox` to mark an element as a scalar. If you use `auto_unbox` you can force an element as an array using `I()`.

**Comment by renkun-ken** [comment]
That's super! Sorry for my ignorance :)
