### ISSUE TITLE
jsonlite toJSON fails in x64 R

### ISSUE THREAD

**Issue by AMarthallerMS** [jeroenooms/jsonlite#139]
It looks like jsonlite does not work under 64 bit R.

> serialized <- jsonlite::toJSON(filteredEvents)
Error in FUN(X[[i]], ...) : 
  no such symbol R_base64_decode in package C:/Users/amarth/Documents/R/win-library/3.2/jsonlite/libs/x64/jsonlite.dll

**Comment by jeroenooms** [comment]
No, you messed up your installation. Please reinstall:

```r
install.packages("jsonlite")
```

**Comment by jeroenooms** [comment]
Make sure `jsonlite` is **not loaded** when you are reinstalling it.

**Comment by AMarthallerMS** [comment]
That was the issue. I had an orphaned R process that prevented a clean update.
