### ISSUE TITLE
Exponential notation

### ISSUE THREAD

**Issue by emilbayes** [jeroenooms/jsonlite#144]
I can't seem to find this referenced anywhere, and I gather from [`num_to_char.c`](https://github.com/jeroenooms/jsonlite/blob/c3bf8a5a6df9fbedb3ed845212de135980b7484d/src/num_to_char.c) that it's not possible, but can you export numbers using exponential notation? I'm dealing with numbers ranging from 0.1 to 1e-7, and expressing them in exponential/scientific/engineering notation would save a great deal of space.

**Comment by emilbayes** [comment]
Oh, didn't read carefully enough: [`num_to_char.c#L63-L65`](https://github.com/jeroenooms/jsonlite/blob/c3bf8a5a6df9fbedb3ed845212de135980b7484d/src/num_to_char.c#L63-L65). However I can't seem to trigger this from R. When will it choose scientific notation over lots of decimal places?

**Comment by jeroenooms** [comment]
Try setting `use_signif=TRUE` 

```r
x <- 10^(-15:15)
toJSON(x, use_signif=TRUE)
```
