### ISSUE TITLE
request: include offset of first parsing error

### ISSUE THREAD

**Issue by r2evans** [jeroenooms/jsonlite#146]
I have a data source that, for whatever reason, is releasing illegal JSON. A minimal representative example:

```json
{"info":""hello world" by: somebody important"}
```

The parser correctly reports this as an error. Unfortunately, the source is unwilling (uncaring?) to fix the issue, and since I have to get the data, I need to react. Unfortunately, the error by `fromJSON`, as informative about the *type* of error, doesn't help me nail down *where* the error is within the string:

```
Error: lexical error: invalid char in json text.
                             {"info":""hello world" by: somebody impor
                     (right here) ------^
```

Though human-readable, if I'm to go in and try to fix it with a scalpel, I need to know where to start looking. (The actual string is ~300k chars.)

Is there a straight-forward way to get the character offset of the first parsing error of the string? I wouldn't expect any fixing or multiple error locations, just the first one. In the example above, it would be `11L` (the "h" after the two double-quotes).

(Also, is the arrow pointing to the wrong character? I expected the `h` to trigger it, not the `e`.)

**Comment by jeroenooms** [comment]
Added this in https://github.com/jeroenooms/jsonlite/commit/9b9c71b7d12512ce9e38524e5ae4cb156fed27d8. The `validate()` function now includes an `offset` attribute:

```r
out <- jsonlite::validate('{"foo":123, "bar":truxe}')
attr(out, "offset")
```

**Comment by r2evans** [comment]
Great, thanks Jeroen!

**Comment by jeroenooms** [comment]
Can you close this issue if this solves your problem?

**Comment by r2evans** [comment]
(I referenced this in a [recent StackOverflow answer](https://stackoverflow.com/a/47296442/3358272).)
