### ISSUE TITLE
lexical error: invalid char in json text

### ISSUE THREAD

**Issue by shubham1637** [jeroenooms/jsonlite#147]
Hi, 
I am trying to get JSON data from github but I always see this issue.
**text <- readLines(curl("https://github.com/localytics/data-viz-challenge/blob/master/data.json"))
mydata <- fromJSON(text)**
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang="en"
                     (right here) ------^

If I download the file and then read it directly I don't see any issue. 

I tried by giving url directly into fromJSON function, I still get the error.
**mydata <- fromJSON("https://github.com/localytics/data-viz-challenge/blob/master/data.json")**
Error in feed_push_parser(readBin(con, raw(), n), reset = TRUE) : 
  lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang="en"
                     (right here) ------^

Do you know how to resolve this issue?

Session info -----------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-09-13                  

Packages -------------------------------------------------------------------
 package  * version date       source        
 curl     * 1.2     2016-08-13 CRAN (R 3.3.1)
 devtools   1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest     0.6.10  2016-08-02 CRAN (R 3.3.1)
 jsonlite * 1.0     2016-07-01 CRAN (R 3.3.1)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.1)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.1)

**Comment by jeroenooms** [comment]
You are trying to read an html page. You want to use the link with the **raw** data: https://raw.githubusercontent.com/localytics/data-viz-challenge/master/data.json
