### ISSUE TITLE
Data frame created with duplicate column names

### ISSUE THREAD

**Issue by charlesgshirley** [jeroenooms/jsonlite#151]
The following results in a data frame that has about 8800 columns, three of which have duplicated column names:
test.l2 <- fromJSON("z_scratch/coo.31924009746854.basic.json", flatten=TRUE)
The data frame is the element test.l2$features$pages.
A copy of the JSON file is available at https://dl.dropboxusercontent.com/u/29281359/coo.31924009746854.basic.json.
Out of about 20 files I have processed so far, 2 have had this problem.
I have verified that the JSON file contains only one instance of data that results in duplicate column names.

**Comment by jeroenooms** [comment]
You probably want to use

```r
test.l2 <- fromJSON("z_scratch/coo.31924009746854.basic.json", simplifyVector = FALSE)
```

**Comment by charlesgshirley** [comment]
That leaves deeply nested lists instead of a data frame that already has essentially the structure I want. That's why I went with "flatten=TRUE" after some trial and error. It looks like I'll need to deal with the lists instead. Thanks for the quick reply.
