### ISSUE TITLE
toJSON() and fromJSON() are not inverses of each other wrt NULLs?

### ISSUE THREAD

**Issue by jennybc** [jeroenooms/jsonlite#154]
I am writing an R list to file via `toJSON()`. Then reading it back into an R list via `fromJSON(..., simplifyDataFrame = FALSE)`. Elements that were `NULL` in the source list reappear as `list()` in the derived list. Is this how it should be?

Here's an example that doesn't involve writing to file:

``` r
library(jsonlite)
x <- list(a = "a", b = NULL)
toJSON(x)
#> {"a":["a"],"b":{}}
fromJSON(toJSON(x))
#> $a
#> [1] "a"
#> 
#> $b
#> named list()
all.equal(x, fromJSON(toJSON(x)))
#> [1] "Component \"b\": target is NULL, current is list"
```

**Comment by jeroenooms** [comment]
Yes this is a limitation, but there is no better solution. See also https://github.com/jeroenooms/jsonlite/issues/29. However note that even though `NULL` and `named list()` are not the same, they are conceptually nearly identical:

```r
identical(NULL, pairlist()) # TRUE
```

Effectively `NULL` is zero-length pairlist in R. However the difference between pairlists and regular lists in R is an implementation detail; they both turn into regular lists after roundtripping to json.

**Comment by jeroenooms** [comment]
But yes this is definitely intended behaviour :-) I thought very long about it back then and `{}` is the only correct json represenation of an R `NULL` type.

**Comment by chrisknoll** [comment]
Hi, @jeroen,
I understand your reasoning (about NULL being an empty pairlist) but why is this the case:

```
fromJSON('{"x":null, "y":[1,null,3]}')
$x
NULL

$y
[1]  1 NA  3
```

Why wasn't x returned as 'NA' ?  I would have expected the NULL be be returned if the json was:
```
{\"x\":{}, \"y\":[1,null,3]}
```

However this returns:
```
> jsonlite::fromJSON('{"x":{}, "y":[1,null,3]}')
$x
named list()

$y
[1]  1 NA  3
```

**Comment by jeroen** [comment]
> Why wasn't x returned as 'NA' ?

In R, `NA` is actually typed vector of length 1. Therefore javascript `null` gets turned into NA only when it appears in a vector.
