### ISSUE TITLE
invalid char in json text for Nan

### ISSUE THREAD

**Issue by shubham1637** [jeroenooms/jsonlite#156]
Hi I am reading a JSON file which has few NaN values
    "VarX": 56, "VarY": NaN, "VarZ": true, "position": 3

Error in feed_push_parser(readBin(con, raw(), n), reset = TRUE) : 
  lexical error: invalid char in json text.

fromJSON function is giving me error for this. I searched and found that I need to manually replace Nan as "NA". But is there any other automated fix for this?

Session Info:
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, darwin14.5.0        
 ui       unknown                     
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Toronto             
 date     2016-11-01

**Comment by jeroenooms** [comment]
No, `NaN` is not JSON, it is JavaScript. See the json specs. Try parsing it in JavaScript:

```r
str <- '{"VarX": 56, "VarY": NaN, "VarZ": true, "position": 3}'
ctx <- V8::v8()
ctx$assign("test", V8::JS(str))
data <- ctx$get('test')
```
