### ISSUE TITLE
jsonlite doesn't correctly encode small floating point numbers

### ISSUE THREAD

**Issue by namelessjon** [jeroenooms/jsonlite#158]
Hi

I recently noticed an issue in encoding small floating point numbers with jsonlite (v 1.1)

This is more noticeable with some than others:
e.g.
``` r
toJSON(3.167e-5)
#=> [0]
# expected: [3.167e-5]
```

Though also the approximations that it makes for other small numbers all result in losing significance, well within the amount that should generally be 'safe' to transmit through floating point numbers, though unlike the previous example, I think they're less wrong.

``` r
toJSON(3.167e-4)
#=> [0.0003]
toJSON(3.167e-3)
#=> [0.0032]
toJSON(3.167e-2)
#=> [0.0317]
```

Note that jsonlite can correctly parse numbers, this is an encoding issue.

**Comment by jeroenooms** [comment]
You can control this with the `digits` argument.

**Comment by namelessjon** [comment]
Thanks for pointing that out, and for your quick answer :smile: 

What confused me was that the case of `toJSON(3.167e-6)` encoded correctly, and preserved all 4 sig figs.  Are very small numbers encoded differently?

**Comment by jeroenooms** [comment]
Yeah it turns out number formatting with decimal digits is really hard and sometimes the number formatter behaves a bit unexpected when it jumps to scientific notation.

**Comment by lassefolkersen** [comment]
I don't understand this sorry. It's super hard to see the system in how it rounds... like in this example below; 3e-6 is not rounded, 3e-5 is rounded to 0, and 3e-4 is not rounded

```
> toJSON(3e-6)
[3e-06]
> toJSON(3e-5)
[0]
> toJSON(3e-4)
[0.0003]
```
Using digits=NA fixes it as you said. But how is it desired behaviour to have only the middle numbers in a range rounded to zero in the default setup.


(I'm using  jsonlite_1.6 on R version 3.4.4)
