### ISSUE TITLE
Suggestion: Allow vector returns from R_parse

### ISSUE THREAD

**Issue by mbannert** [jeroenooms/jsonlite#159]
After our twitter ping-pong, I ran a couple of tests and looked deeper into the code and found potential for speed up by simple means. Here's a quick catch up:

1. Using simplifyVector=FALSE helped a lot and made it a competition in the first place
see this gist: https://gist.github.com/mbannert/14e06edd20bbcb56ababbe005c59cda4

2. Reading the documentation carefully helped to understand that turning the JSON rows that my database returns as a character vector should be collapsed to a scalar json array: 
`jsn_arr <- sprintf("[%s]",paste0(out,collapse = ","))`

3. Still one problem remains. While `RJSONIO` returns a vector if possible, `jsonlite` seems to ALWAYS return a list. At least this is what I understand from reading the comments in `R_parse` and following the R functions through debug mode. R's `unlist` is super slower, coercion like `as.numeric` or as.character is substantially faster, but of course you can't beat RJSONIO here which doesn't have to do it at all. 
Hence I wonder if it would be possible to make R_parse return a vector on the lowest level. Maybe we could pass a parameter to C that let's it return a vector, so there would be no difficult checks to do.

**Comment by jeroenooms** [comment]
The `simplifyVector` argument determines if `fromJSON` returns a list or a vector. There is a bit of extra overhead in this simplification. 

Can you please post reproducible code here (as in: it runs out of the box) to show your performance benchmarks? I feel you might be doing something wrong but it's not clear how exactly you are calling `fromJSON`.

**Comment by mbannert** [comment]
Finally here's your reproducible example :) . Took me a while, had an ugly error when uploading the .RData sample to github. So it's on an AWS EC2 now. 

```
# make sure RJSONIO and jsonlite are installed!
# libraries are not loaded because of masking.

# PostgreSQL returns a character vector. All elements of these character vector
# are JSON. This file on my AWS simulates this db_return vector, which is the starting point.
download.file("http://35.156.219.146/db_return.RData",destfile = "db_return.RData")
load("db_return.RData")

# create an JSON array because jsonlite expect it
# otherwise we would have to loop over the vector => slow
jsn_arr <- sprintf("[%s]",paste0(db_return,collapse = ","))
jsn_li <- jsonlite::fromJSON(jsn_arr,simplifyVector = F)
nms <- unlist(lapply(jsn_li,"[[","ts_key"))

# same with RJSONIO
jsn_li_sonio <- RJSONIO::fromJSON(jsn_arr,simplifyVector = F)

# let's inspect one element:
# jsonlite 
class(jsn_li[[1]]$ts_data)
# RJSONIO
class(jsn_li_sonio[[1]]$ts_data)


runComp <- function(litype){
  lapply(litype,function(x){
  freq <- x$ts_frequency
  d_chars <- names(x$ts_data)
  ts_data <- suppressWarnings(as.numeric(x$ts_data))
  
  d <- as.Date(d_chars[1])
  y <- as.numeric(format(d,"%Y"))
  p <- as.numeric(format(d,"%m"))

    if(freq == 4){
      period <- (p -1) / 3 + 1
    } else if(freq == 12){
      period <- p
    } else if(freq == 1){
      period <- NULL  
    }
    # create the time series object but suppress the warning of creating NAs
    # when transforming text NAs to numeric NAs
    ts(ts_data,
       start=c(y,period),
       frequency = freq)
  })
  }


# Since I want to turn this into a ts object 
# a vector is much faster to handle:

library(microbenchmark)
# ignore the warning it's just because turning char NA to numeric NAs
microbenchmark(
  l_lite <- runComp(jsn_li),
  l_sonio <- runComp(jsn_li_sonio),
  times = 1000
)

# on my macbook pro 2.6 GHz Intel Core i5, 6 GB 1600 MHz DDR3
# Unit: milliseconds
# expr      min      lq     mean   median       uq        max neval
# l_lite <- runComp(jsn_li) 2.100660 2.16461 2.446527 2.215188 2.304111 104.596546  1000
# l_sonio <- runComp(jsn_li_sonio) 1.762334 1.80983 1.960162 1.847851 1.937155   5.627464  1000
```

**Comment by jeroenooms** [comment]
Perhaps I don't understand your issue completely, but it looks like you are not benchmarking `jsonlite` or `RJSONIO` at all? The `runComp` function does not contain any calls to `fromJSON` ?

Here is what I see:


```r

# PostgreSQL returns a character vector. All elements of these character vector
# are JSON. This file on my AWS simulates this db_return vector, which is the starting point.
download.file("http://35.156.219.146/db_return.RData",destfile = "db_return.RData")
load("db_return.RData")
jsn_arr <- sprintf("[%s]",paste0(db_return,collapse = ","))

library(microbenchmark)
microbenchmark(
  jsonlite1 = jsonlite::fromJSON(jsn_arr),
  jsonlite2 = jsonlite::fromJSON(jsn_arr, simplifyVector = FALSE),
  RJSONIO = RJSONIO::fromJSON(jsn_arr),
  times = 1000
)

```

And output:

```
Unit: milliseconds
      expr      min       lq     mean   median       uq       max neval cld
 jsonlite1 5.709895 5.889492 6.298099 5.968843 6.157690 49.646145  1000   c
 jsonlite2 1.325837 1.356607 1.415327 1.377406 1.412886  3.842336  1000 a  
   RJSONIO 2.312697 2.372632 2.469494 2.404608 2.458550  4.491623  1000  b 
```

**Comment by mbannert** [comment]
Thanks for the effort you put in this. Yes, you are totally right. `jsonlite` does win the obvious battle after I followed your suggestion to set `simplifyVector = FALSE`. But this victory is misleading -- at least for my application, because `jsonlite` produces a list vs. a vector.  (look at the `ts_data` part of the `jsn_li` vs. the `ts_data` part of the `jsn_li_sonio`) . 

And that list is considerably slower to coerce to numeric than the vector. So the point is: yes `jsonlite` wins the pure `fromJSON` comparison but leaves you stuck with something that's slower than what `RJSONIO` delivers. Hence I suggested to pass a parameter to the R_parse C function that tells it not to return a list but a vector (while the default behavior is to do what it does).

**Comment by jeroenooms** [comment]
Well jsonlite and rjsonio implement a different mapping between JSON and R objects. For your data, `jsonlite` returns a data frame and `RJSIONIO` returns a list, so it's difficult to compare them. 

I think what you really want to know is given the data `jsn_li`, how do you optimize the code to get it into the format you want (after the json parsing has happened). Because it looks like that is the part that is slow for you, not the parser itself.

**Comment by mbannert** [comment]
Yes, the parser itself is not slow. Agreed. Problem is that, I already use one of the faster operations (`as.numeric`), so there is not much to optimise afterwards. It all boils down to the fact that 
`as.numeric(ts_data)` out of the `jsonlite` `list/data.frame` is slower than as.numeric(ts_data) for the `RJSONIO` returns a vector. Note I am solely talking about the `ts_data` object inside the list.

The point is, there is not much room for optimisation because is just `as.numeric`, everything else is equally fast/slow. Since I can't optimise as numeric, all I can do is adjust the input. And the input is what `jsonlite` returns. I understand you're using `yajl` here, but if I knew how to tweak the `yajl` return before giving it back to R, that's were I could gain some performance.

**Comment by jeroenooms** [comment]
Sorry but I can't solve this problem for you. You can either use `jsonlite` with the default settings to get a nice data frame, or you can set `simplifyVector = FALSE` to only parse the json, which is faster, but then you need to process the data yourself using your favorite packages.

Your [example data](https://gist.github.com/mbannert/14e06edd20bbcb56ababbe005c59cda4) does not have any javascript arrays, so I don't understand what you expect to gain by returning vector instead of list. But from your example it looks like the performance bottlenecks is not the json parser but rather your code to manipulate the output.

**Comment by mbannert** [comment]
I understand you want to close this :) . But since you referred to my outdated example in the closing argument, I think this might be a misunderstanding. I would appreciate a lot if you could have a look at this code (it's reproducible and uses the most recent json example which is an array). Please have a look at the output objects at the end. 

``` 
download.file("http://35.156.219.146/db_return.RData",destfile = "db_return.RData")
load("db_return.RData")
jsn_arr <- sprintf("[%s]",paste0(db_return,collapse = ","))

library(microbenchmark)
microbenchmark(
  jsonlite1 = jsonlite::fromJSON(jsn_arr),
  jsonlite2 = jsonlite::fromJSON(jsn_arr, simplifyVector = FALSE),
  RJSONIO = RJSONIO::fromJSON(jsn_arr),
  times = 1000
)
# yes, jsonlite is the FASTEST ! But .... 

jsonlite2 <- jsonlite::fromJSON(jsn_arr, simplifyVector = FALSE)
rjs <- RJSONIO::fromJSON(jsn_arr)

# How can I get a vector for ts_data??
jsonlite2[[1]]$ts_data  # list
rjs[[1]]$ts_data # vector
```
There is one clear question: Is it possible to get a vector for ts_data, just like RJSONIO does?
In the end I want to coerce these ts_data to `ts` objects and having to do it with a list as opposed to vector hurts speed wise. 

Sorry for re-opening this. Feel free to close it, if you still think it is not related to `jsonlite ` / can't help. I would really prefer to use your package here :). Thanks for the effort you put into this.

**Comment by jeroenooms** [comment]
I think you need `unlist(jsonlite2[[1]]$ts_data, recursive = FALSE)` to get the same as rjsonio.

**Comment by jeroenooms** [comment]
You need `unlist(jsonlite2[[1]]$ts_data, recursive = FALSE)` to get the same as rjsonio. From my benchmark this is still faster than RJSONIO:

```r
download.file("http://35.156.219.146/db_return.RData",destfile = "db_return.RData")
load("db_return.RData")
jsn_arr <- sprintf("[%s]",paste0(db_return,collapse = ","))

# Using jsonlite
test1 <- function(){
  out <- jsonlite::fromJSON(jsn_arr, simplifyVector = FALSE)
  unlist(out[[1]]$ts_data, recursive = FALSE)
}

# using RJSION
test2 <- function(){
  RJSONIO::fromJSON(jsn_arr)[[1]]$ts_data
}

# Verify that result is equal
all.equal(test1(), test2())

library(microbenchmark)
microbenchmark(
  jsonlite = test1(),
  RJSONIO = test2(),
  times = 100
)
```

Gives me:

```
Unit: milliseconds
     expr      min       lq     mean   median       uq      max neval cld
 jsonlite 1.470405 1.563977 1.766495 1.672471 1.904127 2.733880   100  a 
  RJSONIO 2.416496 2.579380 2.983007 2.875730 3.314351 4.411895   100   b
```

**Comment by mbannert** [comment]
Thanks for the extra mile, man. I think the comparison is not quite fair because the additional cost of `unlist` is only paid once. If the JS array results in a list with multiple elements, every single one of these list elements has a `ts_data` sub element. Hence one would have to run `unlist` several times making it more expensive. Also `as.numeric` can be cheaper sometimes, but has essentially the same problem. I don't think you can be much faster than `unlist` or `as.numeric` when coercing a list into a vector. So there's not much to optimise other than not having to run unlist because C returned a vector.

**Comment by mbannert** [comment]
Ok, I guess this can be closed now. I run more tests and realised the dynamic is pretty non-linear depending on the number of elements. Sometimes the additional `unlist` cost weighs higher sometimes not. However, thanks for your help! I learned a lot of tiny things that speeded the process up (using recursive = F, making sure to really pass a JS array). For what it's worth I switch to `jsonlite` now 👍 .

 If there'll ever be a C level detection whether the innermost part of a JSON is a key value pair and can thus be returned as a vector – let me know :) !
