### ISSUE TITLE
nested data.frame as data.table

### ISSUE THREAD

**Issue by jangorecki** [jeroenooms/jsonlite#40]
I have quite complex result in json like this: https://blockchain.info/address/1DP2zBa3X561sRLUcFAh9emEeQXkqkHphA?format=json
It is parsed as list with data.frame with data.frame with data.frame.
Is there any trick (option?) I can make to have all those data.frame already stored as data.table?

Kind of simple `setDT()` ([man](https://github.com/Rdatatable/data.table/blob/master/man/setDT.Rd)) on each created data.frame by jsonlite.

The bests would be to have it during the parsing to do not have overheat related to recursive checking whole parsed json with data.frames.

If there is nothing special we can do maybe I can make a FR for an option like that:
`options("jsonlite.on.data.frame" = my_custom_postprocess_fun_to_be_applied_on_all_DF())`
?

**Comment by jangorecki** [comment]
just in case if somebody would be looking for a similar solution, I've ended up with such a simple wrapper:
```r
use.data.table <- function(x, use = getOption("use.data.table")){
    if(isTRUE(use)){
        if(!requireNamespace("data.table", quietly = TRUE)) stop("Cannot use 'use.data.table' without having data.table package installed.")
        else {
            if(is.data.table(x)) x
            else if(is.data.frame(x)) data.table::setDT(x)
            else if(is.list(x)) lapply(x, use.data.table, use = use)
            else x
        }
    } else x
}
```

**Comment by mattpollock** [comment]
One use case is that data.table handles printing nested structures better (at least within RStudio). For example, the following was parsed from log messages containing some character columns and some json strings in columns. 

```
> dt
                     job_id                              workflow_id map_counters total_counters
 1: job_1456924233345_39216                                       NA <data.frame>   <data.frame>
 2: job_1456924233345_39384 pig_96a75fb6-7f93-47a5-a81d-523c8a303f3c <data.frame>   <data.frame>
 3: job_1456924233345_39398 pig_873c55a0-ebf1-4fbd-a4bd-77ca695245f3 <data.frame>   <data.frame>
 4: job_1456924233345_39405 pig_873c55a0-ebf1-4fbd-a4bd-77ca695245f3 <data.frame>   <data.frame>
 5: job_1456924233345_39412 pig_798594f1-f0b5-4a7c-be99-a43dbc93867f <data.frame>   <data.frame>
 6: job_1456924233345_39419                                       NA <data.frame>   <data.frame>
 7: job_1456924233345_39426 pig_ba40d4ad-74a9-4a3c-a519-05f99fd92be9 <data.frame>   <data.frame>
 8: job_1456924233345_39433 pig_9167e1e0-300a-4b7a-89c0-abc7c385f304 <data.frame>   <data.frame>
 9: job_1456924233345_39440 pig_798594f1-f0b5-4a7c-be99-a43dbc93867f <data.frame>   <data.frame>
10: job_1456924233345_39447 pig_798594f1-f0b5-4a7c-be99-a43dbc93867f <data.frame>   <data.frame>
```
