### ISSUE TITLE
Handling of Unicode characters

### ISSUE THREAD

**Issue by asieira** [jeroenooms/jsonlite#5]
See how the behavior of rjsonlite differs from rjson in the following case:

A short snippet of code that demonstrates the problem:

```
> library(jsonlite)
> nchar(fromJSON("{ \"S\": \"L\\u00e9vis\"\n        }")$S)
Error in nchar(fromJSON("{ \"S\": \"L\\u00e9vis\"\n        }")) : 
  invalid multibyte string 1
```

See how ‘rjson’ handles the same string, which does not cause the error:

```
> library(rjson)
> fromJSON("{ \"S\": \"L\\u00e9vis\"\n        }")
$S
[1] "Lévis"
> detach("package:rjson", unload=TRUE)
> library(jsonlite)
> fromJSON("{ \"S\": \"L\\u00e9vis\"\n        }")
$S
[1] "L\xe9vis"
```

It is worth mentioning that RJSONIO has the exact same issue, so this might be located in the code that rjsonlite shares with it.

**Comment by kominag** [comment]
For me, I save the script file in UTF-8 on linux. That works.
