### ISSUE TITLE
Add support for UTF-16LE

### ISSUE THREAD

**Issue by rynes** [jeroenooms/jsonlite#63]
RFC 4627 (JSON) says that "JSON text SHALL be encoded in Unicode. The default encoding is UTF-8." Further, it says that other UTF formats can be determined from the first 4 octets. In my data it maps to UTF-16LE (which is correct.) 

When I use fromJSON() to convert into an r object using this data directly I get an error: 

Error: Argument 'txt' must be a JSON string, URL or path to existing file 
Execution halted 

But txt is a valid JSON string that is encoded in UTF-16LE format. 

Now if I use iconv() to convert from UTF-16LE to UTF-8 before I use fromJSON() -- then it works perfectly. 

What I want is to have fromJSON() figure out unicode formats other than UTF-8 automatically in order to comply with RFC 4627.

**Comment by jeroenooms** [comment]
It looks to me like R does not support UTF8:

```s
> iconv("foo", from = "UTF-16LE", to = "UTF-8")
[1] NA
```

**Comment by jeroenooms** [comment]
I don't think this issue has anything to do with jsonlite. R doesn't support your string in the first place. You need to read data into an R supported type before you can use jsonlite.

**Comment by rynes** [comment]
Please refer to the R output below:
##### lines 1 - 9 read data from a sqlite database and put it into a dataframe "data"
##### lines 10 - 16 print this data showing that it is UTF-16LE format
##### lines 17 - 18 convert UTF-16LE to UTF-8 (note: R does support UTF-16LE and UTF-8)
##### lines 19 - 20 use fromJSON to convert UTF-8 to JSON (fromJSON works on UTF-8)
##### lines 21 - 26 print JSON data to show it is JSON format (fromJSON works on UTF-8)
##### lines 27 - 30 use fromJSON on original UTF-16LE data (fromJSON does not work on UTF-16LE)

     1  > stmt    <- 'SELECT value from ItemTable where key = "marked_read_urls";'
     2	> datFile <- "https_news.ycombinator.com_0.localstorage"
     3	> dbcon   <- dbConnect(dbDriver("SQLite"), dbname = datFile)
     4	> res     <- dbSendQuery(dbcon, stmt)
     5	> data    <- dbFetch(res, n = 1)
     6	> dbClearResult(res)
     7	[1] TRUE
     8	> dbDisconnect(dbcon)
     9	[1] TRUE
    10	> # show that data$value is UTF-16LE with no BOM
    11	> print (data$value)
    12	[[1]]
    13	    [1] 7b 00 22 00 75 00 6e 00 64 00 65 00 66 00 69 00 6e 00 65 00 64 00 22 00
    14	   [25] 3a 00 31 00 34 00 31 00 39 00 38 00 37 00 30 00 30 00 31 00 35 00 32 00
    15	   [49] 35 00 36 00 2c 00 22 00 68 00 74 00 74 00 70 00 3a 00 2f 00 2f 00 77 00
    16	   [73] 77 00 77 00 2e 00 74 00 65 00 64 00 75 00 6e 00 61 00 6e 00 67 00 73 00
truncated
    17	> # convert from UTF-16LE to UTF-8
    18	> jsondata <- iconv(data$value, from = "UTF-16LE", to = "UTF-8")
    19	> # use fromJSON to convert from UTF-8 to JSON
    20	> f <- fromJSON(jsondata, simplifyDataFrame = TRUE, flatten = TRUE)
    21	> # print converted data showing it is JSON
    22	> print(head(f))
    23	$undefined
    24	[1] 1419870015256
    25	$`http://www.tedunangst.com/flak/post/some-gripes-about-nacl`
    26	[1] 1419870015256
truncated
    27	> # try to convert UTF-16LE data using fromJSON --> ERROR MESSAGE
    28	> print(fromJSON(data$value))
    29	Error: Argument 'txt' must be a JSON string, URL or path to existing file.
    30	Execution halted

**Comment by jeroenooms** [comment]
What is the output of `rawToChar(data$value)`?

**Comment by rynes** [comment]
> k <- rawToChar(data$value)
Error in rawToChar(data$value) : argument 'x' must be a raw vector
Execution halted

**Comment by jeroenooms** [comment]
OK I meant `rawToChar(data$value[[1]])`

**Comment by rynes** [comment]
> k <- rawToChar(data$value[[1]])
Error in rawToChar(data$value[[1]]) : 
  embedded nul in string: '{\0"\0u\0n\0d\0e\0f\0i\0n\0e\0d\0"\0:\01\04\01\09\08\07\00\00\01\05\02\05\06\0,\0"\0h\0t\0t\0p\0:\0/\0/\0w\0w\0w\0.\0t\0e\0d\0u\0n\0a\0n\0g\0s\0t\0.\0c\0o\0m\0/\0f\0l\0a\0k\0/\0p\0o\0s\0t\0/\0s\0o\0m\0e\0-\0g\0r\0i\0p\0e\0s\0-\0a\0b\0o\0u\0t\0-\0n\0a\0c\0l\0"\0:\01\04\01\09\08\07\00\00\01\05\02\05\06\0,\0"\0h\0t\0t\0p\0:\0/\0/\0w\0w\0w\0.\0b\0b\0c\0.\0c\0o\0m\0/\0n\0e\0w\0s\0/\0t\0e\0c\0h\0n\0o\0l\0o\0g\0y\0-\03\00\06\02\03\06\01\01\0"\0:\01\04\01\09\08\07\00\00\01\05\02\05\06\0,\0"\0h\0t\0t\0p\0:\0/\0/\0n\0i\0m\0-\0l\0a\0n\0g\0.\0o\0r\0g\0/\0n\0e\0w\0s\0.\0h\0t\0m\0l\0#\0Z\02\00\01\04\0-\01\02\0-\02\09\0-\0v\0e\0r\0s\0i\0o\0n\0-\00\0-\01\00\0-\02\0-\0r\0e\0l\0e\0a\0s\0e\0d\0"\0:\01\04\01\09\08\07\00\00\01\05\02\05\06\0,\0"\0h\0t\0t\0p\0:\0/\0/\0n\0i\0m\0-\0l\0a\0n\0g\0.\0o\0r\0g\0/\0t\0u\0t\01\0.\0h\0t\0m\0l\0"\0:\01\04\01\09\08\07\00\00\01\05\02\05\06\0,\0"\0h\0t\0t\0p\0:\0/\0/\0w\0w\0w\0.\0r\0e\0u\0t\0e\0r\0s\0.\0c\0o\0m\0/\0a\0r\0t\0i\0c\0l\0e\0/\
Execution halted

**Comment by jeroenooms** [comment]
Okay so R doesn't support the UTF16 string. The only way to do this is manually converting the data to UTF8 as you do in your example using:
   
     iconv(data$value, from = "UTF-16LE", to = "UTF-8") 

It is impossible to do this automatically in jsonlite because there is no way for R to know that a string is UTF16.

**Comment by rynes** [comment]
http://www.ietf.org/rfc/rfc4627.txt
"The application/json Media Type for JavaScript Object Notation (JSON)"
 tells you how to figure this out by looking at the first 4 bytes (even if there is no BOM)

![2014-12-29-09-42-44-www ietf org-rfc-rfc4627 txt](https://cloud.githubusercontent.com/assets/8673110/5594793/c4e69958-9221-11e4-86d3-8a08b005aa19.jpg)
