### ISSUE TITLE
View

### ISSUE THREAD

**Issue by markdanese** [jeroenooms/jsonlite#65]
It looks like jsonlite has its own View function that takes precedence over the one from the utils package.  This causes some issues with RStudio's View.  In particular, the object being viewed loses its name in the tab in RStudio, and is replaced by "x".  I am not sure where the problem resides, but I had brought this to RStudio's attention and then I realized it was an issue caused only when jsonlite is used.  

By the way, jsonlite is great. Other than this issue, it has been a great help.

**Comment by jeroenooms** [comment]
Thanks. Is it just the title, or have you found other problems?

**Comment by jeroenooms** [comment]
I have implemented a fix. Can you try the latest version and see if there are any additional problems?

```s
library(devtools)
install_github("jeroenooms/jsonlite")
```

**Comment by markdanese** [comment]
That seems to have done it.  Thanks very much.  I don't see any other problems.
