### ISSUE TITLE
toJSON discards names on atomic vectors.

### ISSUE THREAD

**Issue by michaelochurch** [jeroenooms/jsonlite#68]
Here's a reproduction. 

    > toJSON(c(a = 1, 2, 3))
    [1,2,3]

This is inconsistent with the typical handling of lists, which is to make them objects if there are named fields. 

    > toJSON(list(a = 1, 2, 3))
    {"a":[1],"2":[2],"3":[3]}
    > toJSON(list(1, 2, 3))
    [[1],[2],[3]]

I think it's fairly obvious that we want atomic vectors *without* names to be turned into arrays. However, I'd argue equally strongly that when there are names on the fields, we should use an object instead of losing that information.

**Comment by jeroenooms** [comment]
Please have a look at the [jsonlite paper](http://arxiv.org/abs/1403.2805). Named lists are converted to objects:

```r
x <- list(foo = 1:3, bar=c(T,F))
toJSON(x)
# {"foo":[1,2,3],"bar":[true,false]} 
```

Unnamed lists are converted to arrays:

```r
x <- list(1:3, c(T,F))
toJSON(x)
# [[1,2,3],[true,false]] 
```

Atomic vectors are converted to arrays. Names are deliberately ignored. Use `as.list` if you want to convert it to a list

```r
x <- c(a = 1, 2, 3)
toJSON(x)
# [1,2,3] 
toJSON(as.list(x))
# {"a":[1],"2":[2],"3":[3]} 
toJSON(as.list(x), auto_unbox=TRUE)
# {"a":1,"2":2,"3":3} 
```

**Comment by jeroenooms** [comment]
Close wontfix.
