### ISSUE TITLE
toJSON -- auto_unbox default FALSE adds extra structure, seems counter-intuitive

### ISSUE THREAD

**Issue by pshannon-bioc** [jeroenooms/jsonlite#72]
switching from RJSONIO to jsonlite, I was surprised to see extra structure added -- an array is created in order to enclose every scalar:

 toJSON(list(cmd="abc", payload=list(title="newTitle", proclaim=TRUE)))
     {"cmd":["abc"],"payload":{"title":["newTitle"],"proclaim":[true]}} 

This can be worked around:

toJSON(list(cmd="abc", payload=list(title="newTitle", proclaim=TRUE)), auto_unbox=TRUE)
    {"cmd":"abc","payload":{"title":"newTitle","proclaim":true}} 

but parsimony and naturalness (my subjective sense of them, anyway!) seem to be violated by the default addition of this extra structure.  In order to adopt jsonlite, I must change and test lots of code throughout two large R/Javascript projects.  Speaking from narrow self-interest, I would be very glad if the RJSONIO toJSON policy was restored.

Thanks!
   - Paul Shannon 

I

**Comment by jeroenooms** [comment]
This has been discussed many times. See section 2.1.3 of the jsonlite [paper](http://arxiv.org/pdf/1403.2805v1.pdf) on the argumentation for not auto-unboxing by default. 

If you want, you can easily override the default for your project/package by defining a function like this:

```r
toJSON <- function(..., auto_unbox = TRUE){
  jsonlite::toJSON(..., auto_unbox = auto_unbox)
}
```

We cannot just change defaults of a package that is in use by so many other packages and scripts for your convenience. That would break a ton of stuff and make many people angry.

**Comment by pshannon-bioc** [comment]
Hi Jeroen,

Thanks for your explanation.  I see I am coming way too late to the discussion.  Forgive me for being callow.

For what it's worth -- not very much, I'll wager! -- the promotion of scalars to vectors seems a very R-centric policy.  My own bias is towards seeing json as a language-neutral representation, and so as much as I love R, and value the "every scalar is also a vector of length one" idiom  in context, my use of other languages led me to think in -their- terms -- Javascript in particular -- rather than in R's.

But you have surely heard all that before.   And don't need to hear it again...

I offer thanks for all the good work included in this package, and to you for taking the time to reply.

Best,

 - Paul

**Comment by jeroenooms** [comment]
There is a case to be made for both sides. To me it's not so much about promoting a scalar to a vector (or demoting a vector of length one to a scalar), but about consistency. Calling `toJSON` on a particular object such as a vector should return a predictable json structure (i.e. an array) regardless of the *content* of the data. Anyway it's described in detail in the paper, have a look at it.

**Comment by pshannon-bioc** [comment]
A good, clear paper.  I'm onboard.   Thanks!

Related to this, and if you have a few minutes to consider this...

I'm in the Bioconductor group.  I will have a couple or three packages in the upcoming release, all of which use httpuv and jsonlite.   Maybe you could comment?  We suspect (but do not want) some controversy, or maybe the packages will disappear as fast as they appear.

They are:   BrowserViz, BrowserPlot2D, RCyjs.

The quickest way to see where we hope they will fit is as a complement to Shiny.  My approach is different from Shiny in two ways:  I avoid any attempt to represent Javascript and HTML in R, but instead figure my audience is those who are equally comfortable in (or equally interested in learning) R and Javascript.  

Second, I build upon Hector Corrado Bravo's extension to httpuv -- the daemonized server -- so that full interactivity with R is maintained.   We hope to get the Windows daemon bug squashed very soon.

BrowserViz is the (concrete) base class, with a few operations, and some efforts made to abstract the websocket setup and asynchrony into simple R functions.  BrowserPlot2D is a very rudimentary derived class, uses a bit of d3 to create what -could- mature into a full d3 standin for R's generic xy plotter, with full interactivity.

RCyjs is much meatier package.  Years ago I wrote the first version of Cytoscape.  A few years ago I did RCytoscape.  All along, I felt pretty sure that network visualization needed to be backed up by a real data exploration language and scripted interactivity, along with rendering in the browser.  All of that is quite attainable now.

What do you think?  Any utility or interest in these things?  Or do they -- like my comments on jsonlite :} -- come too late, are a dollar short,  and off-target?

Best,

 - Paul
