### ISSUE TITLE
unserializeJSON is crashing for graph objects from igraph

### ISSUE THREAD

**Issue by veraanadi** [jeroenooms/jsonlite#74]
This little example is crashing the R session:

library(igraph)
library(jsonlite)
test.graph<-graph.empty()
test2<-serializeJSON(test.graph)

#so far it seems to work and test2 looks ok, but ...

test3<-unserializeJSON(test2)
#if this does not crash the session (with my Rstudio, it does) then this will do
test3

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/jsonlite/commit/a00a6fe5db6da3038016d0304d14f0cbbe8f2590. It was all Gabor's fault.

**Comment by gaborcsardi** [comment]
That. Is. A. Lie.

**Comment by veraanadi** [comment]
Great, guys, thank you. :-) Who cares whose fault it was? It works now.
