### ISSUE TITLE
toJSON doesn't support htmlwidgets::JS

### ISSUE THREAD

**Issue by jrowen** [jeroenooms/jsonlite#77]
I've been working on a `htmlwidget` project and am using jsonlite to convert R objects to json.  I'm running into trouble with the special `htmlwidgets::JS` function,
```
jsonlite::toJSON(list(name = "name", settings = list(
  list(A = c(1, 2), func = htmlwidgets::JS("func")))))

Error: No method asJSON S3 class: JS_EVAL
```
The widget I'm using allows me to define functions in the settings json, so I'm looking for an efficient way to support this.  The workaround I've found is to create a separate list of JS calls on the server side and add these to the widget on the client side.  

I realize that this isn't a `jsonlite` issue, and I am hoping you might suggest a better approach or an enhancement to `toJSON` to support `htmlwidgets::JS`.

**Comment by jeroenooms** [comment]
Can you elaborate on your example? What output are you hoping for?

**Comment by timelyportfolio** [comment]
Have you seen https://github.com/ramnathv/htmlwidgets/pull/28?  Sort of the other way around.  htmlwidgets will need to handle this as there is other downstream handling of JS that occurs.  Is there a reason you need jsonlite?  I believe the plan is to switch to jsonlite when Shiny also switches.

**Comment by jrowen** [comment]
See the example [here](http://handsontable.com/demo/heatmaps.html), particularly the `renderer` parameter of the `columns` settings.  

The widget project I'm working on is [`rhandsontable`](https://github.com/jrowen/rhandsontable), and the [`hot_heatmap`](https://github.com/jrowen/rhandsontable/blob/master/R/rhandsontable.R) function uses this workaround.  In this example, I'd like to define the `renderer` parameter as part of the `columns` json created in the widget instead of adding it to the `columns` parameter on the client (see [`render`](https://github.com/jrowen/rhandsontable/blob/master/inst/htmlwidgets/rhandsontable.js)).

**Comment by jrowen** [comment]
@timelyportfolio Maybe my use of `jsonlite` is not necessary in some of these cases--I'll take another look.

It looks like Shiny's switch to `jsonlite` might be [imminent](https://github.com/rstudio/shiny/commit/defedda891d3802e83e0a91ce4b8da6ca1df977f).

**Comment by wch** [comment]
@jrowen, maybe you need `force=TRUE`?

```R
jsonlite::toJSON(list(name = "name", settings = list(
  list(A = c(1, 2), func = htmlwidgets::JS("func")))), force=T)
# {"name":["name"],"settings":[{"A":[1,2],"func":["func"]}]} 
```

**Comment by jeroenooms** [comment]
I have also been thinking about an option to add inline JavaScript syntax (i.e. not json) so that you can do something like:

```r
> toJSON(list(x=123, y = JS("function(){return x*x}")))
```
```js
{
    "x": [ 123 ],
    "y": function(){return x*x}
}
```

That might be useful to generate objects including javascript functions. But of course the drawback is that the output is javascript, not json.

**Comment by jrowen** [comment]
@wch your suggestion eliminated the error message, thanks.  

Since `force = TRUE` just prints the JavaScript as a character string, right now there doesn't appear to be an advantage to wrapping JavaScript in a `htmlwidgets::JS`.  I still need to loop through the parameter array on the client and convert the strings to a functions (I was able to reuse a JavaScript parse function that seems to do the trick).  @jeroenooms, I think your enhancement would eliminate the client-side steps, though.

See the heatmap, validation and conditional formatting examples [here](https://github.com/jrowen/rhandsontable/blob/master/inst/examples/examples.R) where this approach seems to be working.

**Comment by timelyportfolio** [comment]
@jeroenooms, in regards to your thought on inline JavaScript, I ran across this tricky situation to represent in R from plottable [bar example](http://plottablejs.org/examples/bar/).  Any thoughts on how to pass a matrix of JavaScript objects/functions from R?

```
new Plottable.Component.Table([
  [null,    null, title],
  [yLabel, yAxis, lines.merge(plot)],
  [null,    null, xAxis]
])
```

**Comment by yihui** [comment]
I don't think it makes much sense to support `htmlwidgets::JS()` in jsonlite, which is a hack that probably only makes sense to the htmlwidgets package. You should just prepare your data with `JS()`, and throw the whole thing to htmlwidgets, and it will do what you expect it to do (`eval()` the string in JavaScript). When you start thinking about encoding the output of `JS()`, and decode it later in JavaScript (using `eval()`), it probably defeats the design of `htmlwidgets::JS()`. That said, I'm open to hear a practical use case justifying why anyone would ever want to apply `toJSON()` directly to `JS()`.

@timelyportfolio With the latest version of htmlwidgets (>= 0.3.3), you can just prepare your data in this form:

```r
list(
  list(NULL, NULL, JS('Object')),
  list(JS('Object'), JS('Object'), JS('Object')),
  list(NULL, NULL, JS('Object'))
)
```

**Comment by sz-cgt** [comment]
@yihui the problem is that various JS libraries need/want javascript configuration as part of their setup.  See http://stackoverflow.com/q/36888635/5429068 for an example.

Not being able to pass 'raw' javascript through toJSON prevents that.

**Comment by jeroenooms** [comment]
Quoting from my SO answer: the reason you cannot do this with json libraries is that your code is obviously not JSON but JavaScript. A hack would be to treat the literal string as if it were json:

```r
color <- 'Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0.5).get()'
class(color) <- 'json'
series <- list(
  data = list(c(0, 0), c(100, 0), c(100, 100)),
  type = 'polygon',
  color = color
)

jsonlite::toJSON(series, json_verbatim = TRUE, auto_unbox = TRUE)
```

gives:

```js
{"data":[[0,0],[100,0],[100,100]],"type":"polygon","color":Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0.5).get()} 
```

As yihui already mentioned, `htmlwidgets` and `shiny` always use `json_verbatim = TRUE` in their serializer so all you do is to mark your literal strings with the `json` class.

**Comment by mac471** [comment]
I was having the same issue - using jsonlite to write out html files to use d3plus. Would it be possible to document the json_verbatim argument in the help text for the next release?
