### ISSUE TITLE
Issues with flattening

### ISSUE THREAD

**Issue by abresler** [jeroenooms/jsonlite#81]
Jereon, first thanks for helping to create such a fantastic package.  This is the first time I have run into a problem flattening the JSON into a data frame.  Any idea what's going on?

```r
library(jsonlite)
data <- fromJSON("https://www.honestbuildings.com/1.0/job/2560", flatten = TRUE)
## Shows up still a list of 35
```

**Comment by jeroenooms** [comment]
It's because your json doesn't have a data frame structure. Not every json is suitable to be turned into a data frame. Have a look at the [vignette](http://cran.r-project.org/web/packages/jsonlite/vignettes/json-aaquickstart.html).
