### ISSUE TITLE
Allow specifying digits for ISO8601 datetimes

### ISSUE THREAD

**Issue by wch** [jeroenooms/jsonlite#83]
It would be useful to be able to specify the precision of ISO8601 datetimes.

For example:

```R
time <- Sys.time()
jsonlite::toJSON(POSIXt = "ISO8601", time)
# ["2015-03-20T14:32:57"] 
```

In some cases it would be useful to get millisecond precision.

**Comment by jeroenooms** [comment]
I have refactored `asJSON.POSIXt` so that you can specify a `format` parameter. Hope you have a chance to test this.

**Comment by wch** [comment]
It looks like it's working. With the `%OS3` format string, it gives millisecond precision:

```R
toJSON(Sys.time(), format="%Y-%m-%dT%H:%M:%OS3Z")
# ["2015-03-23T11:02:33.140Z"] 
```

**Comment by wch** [comment]
Are you sure you want to use `format` as the argument? I don't feel strongly about this, but IMO, `format` suggests a very general option, whereas a name like `timeFormat` is more informative.

**Comment by jeroenooms** [comment]
Yes maybe, I just took the argument name from `as.character`. I'll change it to `time_format`.

**Comment by jeroenooms** [comment]
The `time_format` argument is now supported in jsonlite 0.9.15:

```r
> toJSON(Sys.time(), time_format = "%Y-%m-%dT%H:%M:%OS3Z")
["2015-03-26T20:42:13.380Z"] 
```
