### ISSUE TITLE
RStudio Packrat and jsonlite load error

### ISSUE THREAD

**Issue by apapanico** [jeroenooms/jsonlite#89]
Hi all,
I have a project in RStudio running packrat and I get the following error message.  Strange thing is even yesterday this was working, maybe even today, but now I can't get around it.  I just updated to the newest Rstudio today.

I *think* the problem is that the Packrat migration script skips the rstudio package and somehow the .onLoad function for jsonlite still needs it.  That kind of doesn't make any sense since it's supposed to be using rstudioapi.  Any thoughts?

```
library(jsonlite)
Error : .onLoad failed in loadNamespace() for 'jsonlite', details:
  call: loadNamespace(name)
  error: there is no package called ‘rstudio’
Error: package or namespace load failed for ‘jsonlite’
```

**Comment by jeroenooms** [comment]
Which version of jsonlite are you using? Please include your `sessionInfo()`

**Comment by apapanico** [comment]
Unreal... error is gone now.  Possibly because of an Rstudio restart.  Your guess is as good as mine.  Sorry for the waste of time.

**Comment by jeroenooms** [comment]
Sometimes there are objects in your workspace that rstudio automatically tries to restore after restarting the R session, that can cause trouble.

**Comment by neverfox** [comment]
Not going away for me, even after restarts:
```
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin14.3.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] formatR_1.2      tools_3.2.0      rstudioapi_0.3.1 knitr_1.9.23     stringr_0.6.2    packrat_0.4.3
```
Seems to have coincided with upgrading to R 3.2.0

**Comment by ysgit** [comment]
Has anyone resolved this issue with R 3.2.0 and jsonlite 0.9.16? It's not working for me, same errpr. Here's my sessionInfo() 

```
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.12.0

loaded via a namespace (and not attached):
 [1] R6_2.0.1         htmltools_0.2.6  tools_3.2.0      rstudioapi_0.3.1 Rcpp_0.11.6     
 [6] digest_0.6.8     xtable_1.7-4     httpuv_1.3.2     mime_0.3         packrat_0.4.3  
```

**Comment by ysgit** [comment]
OK, this fixed it for me

```
packrat::set_opts(external.packages = c("rstudio"))
```

**Comment by sculptor3** [comment]
packrat::set_opts(external.packages = c("rstudio"))  
didn't fix it for me. Does anyone knows what going on with this error?

Error in results[sapply(results, Negate(isTRUE))] : 
  invalid subscript type 'list'
In addition: Warning messages:
1: In FUN("rstudio"[[1L]], ...) :
  Package 'rstudio' not available in repository or locally
2: In symlinkExternalPackages(project = project) :
  The following external packages could not be located:
- "rstudio"

**Comment by dylanbeaudette** [comment]
I am also having this problem, but only when loading the package from within RStudio--from the command line everything works as expected. Details below.

Vanilla R:
```
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] jsonlite_0.9.16
```

RStudio (Version 0.98.983):
```
> library(jsonlite)
Error : .onLoad failed in loadNamespace() for 'jsonlite', details:
  call: NULL
  error: package ‘rstudio’ was built before R 3.0.0: please re-install it
In addition: Warning message:
package ‘jsonlite’ was built under R version 3.2.1 
Error: package or namespace load failed for ‘jsonlite’
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] rstudioapi_0.3.1 tools_3.1.1 
```

I have tried manually sourcing / running the .onLoad() function from the jsonlite package. It seems that there could be a bug in this function that cannot deal with older versions of RStudio. When running the function manually I get:

```
# source this
.onLoad <- function(lib, pkg) {
  rstudioapi <- "rstudioapi"
  if (nchar(Sys.getenv("RSTUDIO")) && requireNamespace(rstudioapi, quietly = TRUE)) {
    isAvailable <- get("isAvailable", envir = asNamespace(rstudioapi))
    if (isAvailable("0.99.324")) {
      remove("View", pos = environment(.onLoad))
    }
  }
}

# run it
.onLoad()

# oops! 
#  Error: package ‘rstudio’ was built before R 3.0.0: please re-install it 
```

Stepping through .onLoad() I see that:

```
isAvailable("0.99.324")
```
is returning an error--no matter what the arguments are.

Thanks for the great package, I hope that this helps.

Dylan

**Comment by daranzolin** [comment]
Is this issue still open? I'm getting the same error as OP, and neither restarting nor 
```
packrat::set_opts(external.packages = c("rstudio")) 
```
provides a fix.

**Comment by jeroenooms** [comment]
I'm going to take out this rstudio workaround.

**Comment by jeroenooms** [comment]
Try reinstalling:

```r
devtools::install_github("jeroenooms/jsonlite")
```
