### ISSUE TITLE
Avoid NIH, depend on base64enc

### ISSUE THREAD

**Issue by flying-sheep** [jeroenooms/jsonlite#93]
[s-u/base64enc](https://github.com/s-u/base64enc) has well-working and fast in-memory base64 en/decoing instead of stomach-churning `tempfile()` hackery.

we really should use that package.

**Comment by jeroenooms** [comment]
I agree, although I would prefer to bundle some C code rather than introducing an additional dependency. Feel free to send a PR.

**Comment by flying-sheep** [comment]
why no depencency?

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/jsonlite/commit/c2a180c692c151146b7702687842976b11c86051 .

**Comment by flying-sheep** [comment]
thanks! still: why no dependency?

**Comment by jeroenooms** [comment]
This is an infrastructural package which should be as minimal as possible. I like the package to be self contained so that it can be installed from the source package, even if there is no internet connection to download dependencies and stuff.

**Comment by flying-sheep** [comment]
i’ve never seen an R installation that doesn’t have a node-esque giant dependency tree, so i really don’t see anyone just installing jsonlite as one of three or so packages.

a quick check showed that of everything depending on jsonlite, only RDataCanvas *just* depends on it, everything else having at least 5 dependencies.

of course it’s your decision…
