### ISSUE TITLE
Building src package fails

### ISSUE THREAD

**Issue by vnijs** [jeroenooms/jsonlite#95]
==> roxygen2::roxygenize('.', roclets=c('rd', 'namespace'))

Documentation completed

==> R CMD build jsonlite

* checking for file ‘jsonlite/DESCRIPTION’ ... OK
* preparing ‘jsonlite’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'R.rsp' not found
Execution halted

Exited with status 1.

**Comment by jeroenooms** [comment]
`install.packages("R.rsp")`

**Comment by vnijs** [comment]
Had niet gedacht dat R.rsp een package was. Bedankt Jeroen!
