### ISSUE TITLE
Bug: Flatten does not work when used with simplifyVector/simplifyDataframe 

### ISSUE THREAD

**Issue by amin04** [jeroenooms/jsonlite#99]
So I have the following json data:

    "[{\"count\":20,\"subject\":{\"name\":\"United States\",\"alpha2\":\"US\"}},{\"count\":3,\"subject\":{\"name\":\"Canada\",\"alpha2\":\"CA\"}},{\"count\":3,\"subject\":{\"name\":\"Trinidad and Tobago\",\"alpha2\":\"TT\"}},{\"count\":2,\"subject\":{\"name\":\"France\",\"alpha2\":\"FR\"}},{\"count\":1,\"subject\":{\"name\":\"Czech Republic\",\"alpha2\":\"CZ\"}},{\"count\":1,\"subject\":{\"name\":\"United Kingdom\",\"alpha2\":\"GB\"}},{\"count\":1,\"subject\":{\"name\":\"Korea, Republic of\",\"alpha2\":\"KR\"}},{\"count\":1,\"subject\":{\"name\":\"Peru\",\"alpha2\":\"PE\"}},{\"count\":1,\"subject\":{\"name\":\"Brazil\",\"alpha2\":\"BR\"}},{\"count\":1,\"subject\":{\"name\":\"Taiwan, Province of China\",\"alpha2\":\"TW\"}},{\"count\":1,\"subject\":{\"name\":\"Namibia\",\"alpha2\":\"NA\"}},{\"count\":1,\"subject\":{\"name\":\"Faroe Islands\",\"alpha2\":\"FO\"}},{\"count\":1,\"subject\":{\"name\":\"Barbados\",\"alpha2\":\"BB\"}}]"

When I try

    as.data.frame(fromJSON(jsontext, flatten=TRUE))

it works fine, gives me a flat data frame. However, when I do

    as.data.frame(fromJSON(jsontext, simplifyDataFrame=FALSE, flatten=TRUE))

the flatten option doesn't work at all. Not what I expected.

**Comment by jeroenooms** [comment]
So what do you expect? The docs state that:

 > flatten: automatically flatten nested data frames into a single non-nested data frame

So if you have no data frames in your data, then there is nothing to flatten.

**Comment by amin04** [comment]
Sorry, meant `simplifyVector=False` instead of `simplifyDataFrame=FALSE`.

Those two calls give different results, even though `Flatten=TRUE` for both. Why is that?

**Comment by jeroenooms** [comment]
`simplifyVector=FALSE` implies `simplifyDataFrame=FALSE` because a data frame consists of vectors.

**Comment by amin04** [comment]
So `Flatten=TRUE` won't work together with `simplifyVector=FALSE`?

**Comment by jeroenooms** [comment]
No it won't. simplifyVector=FALSE means that the output will only
contain nested lists, so there are no data frames to flatten.
